// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NET_Gram.Data;

namespace NET_Gram.Migrations
{
    [DbContext(typeof(PostDbContext))]
    [Migration("20190226023941_f")]
    partial class f
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NET_Gram.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption");

                    b.Property<int>("Rating");

                    b.Property<string>("Title");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Caption = "In a field of dreams",
                            Rating = 4,
                            Title = "flowers",
                            URL = "flowers.jpg"
                        },
                        new
                        {
                            ID = 2,
                            Caption = "In a bathtub",
                            Rating = 3,
                            Title = "bubbles",
                            URL = "bubbles.jpg"
                        },
                        new
                        {
                            ID = 3,
                            Caption = "On cloud nine",
                            Rating = 4,
                            Title = "clouds",
                            URL = "cloud.jpg"
                        },
                        new
                        {
                            ID = 4,
                            Caption = "I love food",
                            Rating = 5,
                            Title = "food",
                            URL = "food.jpg"
                        },
                        new
                        {
                            ID = 5,
                            Caption = "I like it",
                            Rating = 4,
                            Title = "makeup",
                            URL = "makeup.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
